# -*- coding: utf-8 -*-
"""Копия блокнота "OrdersFutures.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btZH2bflk6-2ngJb9mj_ko_DRsWzaPkg
"""

pip install python-binance

from binance.client import Client

api_key = ''
secret = ''

client = Client(api_key=api_key, api_secret=secret) #прописать переменные для ключей

balance = client.futures_account_balance()[6]['balance'] #

balance

info = client.futures_exchange_info()

info

symbol = 'ALGOUSDT'

buy_market = client.futures_create_order(symbol='ALGOUSDT', side='BUY', type='MARKET', quantity=20)

take = client.futures_create_order(symbol=symbol, side='SELL', type='TAKE_PROFIT_MARKET', stopPrice='0.3020', closePosition='true')

stop = client.futures_create_order(symbol=symbol, side='SELL', type='STOP_MARKET', stopPrice='0.2940', closePosition='true')

sell_limit = client.futures_create_order(symbol=symbol, side='SELL', type='LIMIT', quantity=20, price='0.3004', timeInForce='GTC')

buy_limit = client.futures_create_order(symbol=symbol, side='BUY', type='LIMIT', quantity=20, price='0.2960', timeInForce='GTC')