# -*- coding: utf-8 -*-
"""ByBitMacd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCCGoSZLhe7mpYkj31KEPD3Q7KTUnpqw
"""

pip install pybit

pip install ta

from pybit import spot
import pandas as pd
import ta

api_key =''
api_secret = ''

session = spot.HTTP(endpoint="https://api.bybit.com")

def klines(symbol):
  kline = session.query_kline(symbol=symbol, interval="1m")
  kline = kline['result']
  df = pd.DataFrame(kline)
  df = df.iloc[:,:6]
  df.columns = ['Time', 'Open', 'High', 'Low', 'Close', 'Volume']
  df = df.set_index('Time')
  df.index = pd.to_datetime(df.index, unit='ms')
  df = df.astype(float)
  return df

def strategy(symbol, qty, open_position = False):

  while True:
    df = klines(symbol)
    if not open_position:
      if ta.trend.macd_diff(df.Close).iloc[-1] > 0 \
      and ta.trend.macd_diff(df.Close).iloc[-2] < 0:
        order = session.place_active_order(symbol=symbol, side='Buy', type='MARKET', qty=qty, timInForce='GTC')
        print(order)
        open_position = True
        break
      
    if open_position:
      while True:
        df = klines(symbol)
        if ta.trend.macd_diff(df.Close).iloc[-1] < 0 \
        and ta.trend.macd_diff(df.Close).iloc[-2] > 0:
          order = session.place_active_order(symbol=symbol, side='Sell', type='MARKET', qty=qty, timInForce='GTC')
          print(order)
          open_position = False
          break

strategy("WLKNUSDT", 10)